config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"


  resources :posts, only: %I[index show create] do
    resources :comments, only: %i[create]
    resources :reactions, only: %i[create destroy]
  end
  resources :users, only: [:show] do
    resources :friendships, only: [:index, :create]
  end
  resources :comments, only: [:destroy]
  resources :reactions, only: [:destroy]
  resources :posts, only: [:destroy]

  get 'search_music', to: "posts#search_music"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :asker, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  attr_reader :search_music
  scope :followed, -> { where(followed: true) }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
  validates :mood, presence: true
  MOODS = %i[😁 😔 🥳 🥹 😒 😡 😴 🤔 🥶]

  def best_reactions
    self.reactions.order(count: :desc)
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def increment_count
    self.count += 1
    self.save!
  end

  def current_user?(current_user)
    self.user == current_user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :reactions
  validates :username, uniqueness: true
  has_many :friendships_as_asker, class_name: "Friendship", foreign_key: :asker_id
  has_many :friendships_as_receiver, class_name: "Friendship", foreign_key: :receiver_id

  def last_posts
    self.posts[0..-2]
  end

  def last_post_day
    self.posts.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post
    if @comment.save!
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friendships = Friendship.where(asker_id: current_user)
  end

  def create
    @friendship = Friendship.new(friendship_params)
    @friendship.asker = current_user
    @friendship.save!
    redirect_to user_friendships_path(current_user)
  end

  private

  def friendship_params
    params.require(:friendship).permit(:receiver_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = params[:mood] ? Post.where(mood: params[:mood]) : Post.all
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def create
    @post = Post.new(mood: post_params[:mood], track_id: post_params[:track_id], content: post_params[:content])
    @post.user = current_user
    if @post.save!
      redirect_to posts_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end

  def search_music
    @spotify_service = GetSpotifyService.new
    @tracks = @spotify_service.get_tracks(params[:track])
    respond_to do |format|
      format.json { render json: { tracks: @tracks } }
    end
  end

  private

  def post_params
    params.require(:post).permit(:mood, :track_id, :content, :search_music)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @reaction = Reaction.find_or_initialize_by(emoji: reaction_params[:emoji], post: @post)
    @reaction.user = current_user
    if @reaction.save
      @reaction.increment_count
      respond_to do |format|
        format.text { render partial: "posts/emoji_list", locals: { post: @post }, formats: [:html] }
      end
    end
  end

  private

  def reaction_params
    params.require(:reaction).permit(:emoji)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @last_posts = @user.last_posts
    @friendship = Friendship.new
  end

  def params_user
    params.require(:users).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wakely</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_emoji_list.html.erb
<% post.best_reactions.each do |reaction| %>
  <li class="emoji-reaction <%= "selected" if reaction.current_user?(current_user) %>">
    <%= reaction.emoji %> <span><%= reaction.count %></span>
  </li>
<% end %>

app/views/posts/_emoji_picker.html.erb
<i class="fa-solid fa-face-grin" data-action="click->emoji-picker#toggle"></i>
<div class="emojis d-none" data-emoji-picker-target="emojiPicker">
  <% %w(👍 ❤️ 😲 😡 😢).each do |emoji| %>
    <div class="emoji" data-action="click->emoji-picker#createReaction"><%= emoji %></div>
  <% end %>
</div>

app/views/posts/_post_form.html.erb
<div data-controller="search-music" data-search-music-value=<%= search_music_path %>>
  <%= simple_form_for @post do |f| %>
  <%= f.input :mood, label: "Comment te sens-tu ?",class:"radius", collection: Post::MOODS %>
  <%= f.input :search_music, label:'Choisis ta musique', input_html: { data: {
                                              search_music_target: "input",
                                              action: 'keyup->search-music#getTracks'
                                            }
                                          } %>
  <%= f.input :track_id, as: :hidden, input_html: { data: { search_music_target:"hiddenInput" }} %>
  <ul data-search-music-target="ul"></ul>
  <%= f.input :content,  label: false, placeholder: 'Commentaire...' %>
  <div class= "d-flex justify-content-end">
    <%= f.submit "Envoyer", class:" btn btn-outline-light rounded-pill" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="banner ">

  <!-- Modal -->
  <div class="modal custom fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Partage ta musique</h1>
          <button type="button" class="btn-close white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "post_form" %>
        </div>

      </div>
    </div>
  </div>
  <img class="logo-wak mb-2 mt-1" src="https://res.cloudinary.com/dsbtmmjt2/image/upload/v1701966700/akely_oyctua.png"
    alt="logo wakely">
  <div class="scrollmenu mx-3 wakely-font">
    <% Post::MOODS.each do |mood|  %>
    <%=link_to mood, posts_path(mood: mood), class:"a-link" %>
    <% end %>
  </div>
  <div class="container-md">
    <%= render "cardpost"%>
    <br>
    <br>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-bottom d-flex justify-content-between">
  <% if user_signed_in? %>


    <div class="navbar-name wakely-font">
      <%= link_to posts_path do %>
      <i class="fa-solid fa-house"></i>
      <% end %>
      <h6 class="align-text-center">Accueil</h6>
    </div>


    <div class="navbar-name wakely-font">
      <%= link_to user_path(current_user) do %>
      <i class="fa-solid fa-user"></i>
      <% end %>
      <h6 class="align-text-center">Profil</h6>
    </div>


    <div class="navbar-name wakely-font">
      <%= link_to posts_path do%>
      <i class="fa-solid fa-plus" data-bs-toggle="modal" data-bs-target="#exampleModal"></i>
      <% end %>
      <h6 class="align-text-center">Créer</h6>
    </div>

    <div class="navbar-name wakely-font">
      <%= link_to user_friendships_path(current_user) do%>
      <i class="fa-solid fa-user-group"></i>
      <% end %>
      <h6 class="align-text-center">Amis</h6>
    </div>


  <% end %>
</nav>

app/views/users/_notification.html.erb
  <div data-controller="notification">
    <i class="fa-solid fa-clock" data-action="click->notification#toggle"></i>
    <div class="timepicker-ui d-none" data-notification-target="timePicker">
      <input data-notification-target="input" type="text" class="timepicker-ui-input" value="12:00 AM" />
      <button data-action="click->notification#setNotification">Valider la notification</button>
    </div>
  </div>

app/views/users/index.html.erb
<% @users.each do |user| %>
 <h1><%= user.username%></h1>
  <%=link_to user.username, user_path(@user)%>
<% end %>